stages:
  train:
    cmd: python mlops/modeling/train.py training.num_epochs=10
    deps:
    - data/processed
    - mlops/modeling/train.py
    - mlops/config/
    outs:
    - models/
    - outputs/
    metrics:
    - reports/metrics.json:
        cache: false
